pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: "Always"
      command:
        - "sleep"
      args:
        - "99d"
    - name: git-cli
      image: "alpine/git:latest"
      command:
        - "sleep"
      args:
        - "99d"
"""
    }
  }
  environment {
    ECR_REGISTRY   = "865683084473.dkr.ecr.eu-west-2.amazonaws.com"
    IMAGE_NAME   = "lesson-8-9-ecr"
    IMAGE_TAG    = "v1.0.${BUILD_NUMBER}"
    COMMIT_EMAIL = "jenkins@localhost"
    COMMIT_NAME  = "jenkins"
  }
  stages {
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh """
            /kaniko/executor \\
              --context `pwd`/lesson-7/django-app-src \\
              --dockerfile `pwd`/lesson-7/django-app-src/Dockerfile \\
              --destination=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \\
              --cache=true
          """
        }
      }
    }
    stage('Update Chart Tag in Git') {
      steps {
        container('git-cli') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_PAT')]) {
            sh '''
              git clone https://${GITHUB_USER}:${GITHUB_PAT}@github.com/${GITHUB_USER}/DevOps-CI-CD.git
              cd DevOps-CI-CD
              git config user.email "$COMMIT_EMAIL"
              git config user.name "$COMMIT_NAME"
              git checkout lesson-8-9
              sed -i "s|    repository: .*|    repository: \\"${ECR_REGISTRY}/${IMAGE_NAME}\\"|" charts/django-app/values.yaml
              sed -i "s|tag: .*\$|tag: \\"$IMAGE_TAG\\"|" charts/django-app/values.yaml
              git add charts/django-app/values.yaml
              git commit -m "Update image tag to $IMAGE_TAG"
              git push origin lesson-8-9
            '''
          }
        }
      }
    }
  }
}