applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/staskut/goit-devops.git
      path: django-chart
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: https://github.com/staskut/goit-devops.git
#    username: YOUR_USERNAME
#    password: YOUR_PASS

repoConfig:
  insecure: "true"
  enableLfs: "true"
