apiVersion: v2
name: django-app
description: A Helm chart for Kubernetesgit ls-tree -r HEAD --name-only | grep django-app
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
    - name: postgresql
      version: "16.4.3"
      repository: "https://charts.bitnami.com/bitnami"
